export const weight = {
  300: "Pretendard300",
  400: "Pretendard400",
  500: "Pretendard500",
  600: "Pretendard600",
};
export const usage = {
  // #region Display
  ".display1": {
    usageWeb: "display1",
    usageMobile: "displayLarge",
    styleNm: "Large",
    webSize: 48,
    mobileSize: 38,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  ".display2": {
    usageWeb: "display2",
    usageMobile: "displayMedium",
    styleNm: "Medium",
    webSize: 44,
    mobileSize: 40,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  ".display3": {
    usageWeb: "display3",
    usageMobile: "displaySmall",
    styleNm: "Small",
    webSize: 40,
    mobileSize: 32,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  // #endregion Display
  // #region Headline
  h1: {
    usageWeb: "h1",
    usageMobile: "headlineLarge",
    styleNm: "Large",
    webSize: 36,
    mobileSize: 29,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  h2: {
    usageWeb: "h2",
    usageMobile: "headlineMedium",
    styleNm: "Medium",
    webSize: 33,
    mobileSize: 27,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  h3: {
    usageWeb: "h3",
    usageMobile: "headlineSmall",
    styleNm: "Small",
    webSize: 30,
    mobileSize: 25,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  // #endregion Headline
  // #region Title
  h4: {
    usageWeb: "h4",
    usageMobile: "titleLarge",
    styleNm: "Large",
    webSize: 27,
    mobileSize: 23,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  h5: {
    usageWeb: "h5",
    usageMobile: "titleMedium",
    styleNm: "Medium",
    webSize: 24,
    mobileSize: 21,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  h6: {
    usageWeb: "h6",
    usageMobile: "titleSmall",
    styleNm: "Small",
    webSize: 21,
    mobileSize: 19,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  // #endregion Title
  // #region Body
  ".p1": {
    usageWeb: "p1",
    usageMobile: "bodyLarge",
    styleNm: "Large",
    webSize: 18,
    mobileSize: 17,
    weight: 400,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  ".p2": {
    usageWeb: "p2",
    usageMobile: "bodyMedium",
    styleNm: "Medium",
    webSize: 15,
    mobileSize: 15,
    weight: 400,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  p: {
    usageWeb: "p3",
    usageMobile: "bodySmall",
    styleNm: "Small",
    webSize: 14,
    mobileSize: 13,
    weight: 400,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  ".p4": {
    usageWeb: "p4",
    usageMobile: "bodyExtraSmall",
    styleNm: "ExtraSmall",
    webSize: 13,
    mobileSize: 12,
    weight: 400,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  // #endregion Body
  // #region Label
  ".label1": {
    usageWeb: "label1",
    usageMobile: "labelLarge",
    styleNm: "Large",
    webSize: 18,
    mobileSize: 17,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  label: {
    usageWeb: "label2",
    usageMobile: "labelMedium",
    styleNm: "Medium",
    webSize: 15,
    mobileSize: 15,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  ".label3": {
    usageWeb: "label3",
    usageMobile: "labelSmall",
    styleNm: "Small",
    webSize: 14,
    mobileSize: 13,
    weight: 600,
    lineHeight: "130%",
    letterSpacing: "0%",
  },
  // #endregion Label
};
export const typography = { weight, usage };
